#----------------------------
#Customize Image by pasit.dev
#----------------------------
version: "3"
services:
#------Nginx Web Server--------
  nginx:
    container_name: nginx
    image: ezynook/data-catalog:nginx
    links:
      - ckan
    ports:
      - "0.0.0.0:${PORT}:80"
#------Ckan Open-D--------
  ckan:
    container_name: ckan
    image: ezynook/data-catalog:ckan
    environment:
      - CKAN_SITE_URL=${IPADDR}:${PORT}
    links:
      - db
      - solr
      - redis
    volumes:
      - ckan_storage:/var/lib/ckan
#------PostgreSQL 11-------
  db:
    container_name: db
    image: ezynook/data-catalog:db
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
#------Solr--------
  solr:
    container_name: solr
    image: ezynook/data-catalog:solr
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index
#------Redis--------
  redis:
    container_name: redis
    image: ezynook/data-catalog:redis

volumes:
  ckan_storage:
  pg_data:
  solr_data: