version: "3"
services:
  nginx:
    container_name: nginx
    image: ezynook/data-catalog:nginx
    restart: always
    links:
      - ckan
    ports:
      - "0.0.0.0:${PORT}:80"
      
  ckan:
    container_name: ckan
    image: ezynook/data-catalog:ckan
    restart: always
    environment:
      - CKAN_SITE_URL=${IPADDR}:${PORT}
    links:
      - db
      - solr
      - redis
    volumes:
      - ckan_storage:/var/lib/ckan

  db:
    container_name: db
    image: ezynook/data-catalog:db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

  solr:
    container_name: solr
    image: ezynook/data-catalog:solr
    restart: always
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data/index

  redis:
    container_name: redis
    image: ezynook/data-catalog:redis
    restart: always
volumes:
  ckan_storage:
  pg_data:
  solr_data:
